openapi: 3.1.0

info:
  title: Lingua API
  description: API for Lingua application
  version: 1.0.0

paths:
  /sections:
    get:
      $ref: "./endpoints/sections.yml#/getAllSections"

  /sections/{sectionNumber}/units:
    get:
      $ref: "./endpoints/units.yml#/getUnitsBySectionNumber"

  /sections/{sectionNumber}/units/{unitNumber}/lessons/{lessonNumber}/variants/{variantNumber}:
    get:
      $ref: "./endpoints/units.yml#/getVariantByNumberInLesson"
